// <auto-generated />
namespace JIC.Crime.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddStoredProcedur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStoredProcedur));
        
        string IMigrationMetadata.Id
        {
            get { return "201712191102241_AddStoredProcedur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
