// <auto-generated />
namespace JIC.Crime.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newcolumninCase_Lawyer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newcolumninCase_Lawyer));
        
        string IMigrationMetadata.Id
        {
            get { return "201810311103405_newcolumninCase_Lawyer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
