//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIC.Base.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JIC.Base.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل توافق على التصديق على الجلسة لهذة القضية.
        /// </summary>
        public static string ApprovCsesessionMessage {
            get {
                return ResourceManager.GetString("ApprovCsesessionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال المرفقات حتى تتمكن من إرسال المحضر.
        /// </summary>
        public static string AttachmentsUnSaved {
            get {
                return ResourceManager.GetString("AttachmentsUnSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف هذة الدائرة .. يوجد قضايا لهذة الدائرة.
        /// </summary>
        public static string CaseConnectedToCircuit {
            get {
                return ResourceManager.GetString("CaseConnectedToCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القضية متواجدة من قبل.
        /// </summary>
        public static string CaseIsExist {
            get {
                return ResourceManager.GetString("CaseIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يلزم وجود متهم واحد و مجني عليه واحد على الأقل بالقضية.
        /// </summary>
        public static string checkPartiesList {
            get {
                return ResourceManager.GetString("checkPartiesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الدائرة مستخدم من قبل.
        /// </summary>
        public static string CircuitExists {
            get {
                return ResourceManager.GetString("CircuitExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من رغيتك في إنهاء العملية؟.
        /// </summary>
        public static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال تاريخ اكبر من تاريخ اليوم.
        /// </summary>
        public static string DateBeforeTodayError {
            get {
                return ResourceManager.GetString("DateBeforeTodayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال التاريخ.
        /// </summary>
        public static string DateFieldError {
            get {
                return ResourceManager.GetString("DateFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال القرارت و الاحكام حتى تتمكن من إرسال المحضر.
        /// </summary>
        public static string DecisionUnSaved {
            get {
                return ResourceManager.GetString("DecisionUnSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال إثبات حضور المتهمين حتى تتمكن من إرسال المحضر.
        /// </summary>
        public static string DefectsPresenceUnSaved {
            get {
                return ResourceManager.GetString("DefectsPresenceUnSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى الحذف.
        /// </summary>
        public static string DeleteFaild {
            get {
                return ResourceManager.GetString("DeleteFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم مسح وكيل النيابة ولكن الشخص مربوط بشئ اخر.
        /// </summary>
        public static string DeleteProsecutorNotPeson {
            get {
                return ResourceManager.GetString("DeleteProsecutorNotPeson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        public static string DeleteSucess {
            get {
                return ResourceManager.GetString("DeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء يجب ان يكون اكبر من او يساوى تاريخ البدايه.
        /// </summary>
        public static string Durations {
            get {
                return ResourceManager.GetString("Durations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        public static string EditSucess {
            get {
                return ResourceManager.GetString("EditSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى التعديل.
        /// </summary>
        public static string EditVaild {
            get {
                return ResourceManager.GetString("EditVaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاكد من ادخال حروف فى الاسم والرقم القومى صحيح.
        /// </summary>
        public static string EditVailidation {
            get {
                return ResourceManager.GetString("EditVailidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل رقم البطاقة.
        /// </summary>
        public static string EnterNationalID {
            get {
                return ResourceManager.GetString("EnterNationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إختر النيابة الخاصة بوكيل النيابة.
        /// </summary>
        public static string EnterProsecution {
            get {
                return ResourceManager.GetString("EnterProsecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال إسم وكيل النيابة.
        /// </summary>
        public static string EnterProsecutor {
            get {
                return ResourceManager.GetString("EnterProsecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطا فى حفظ الترنيب.
        /// </summary>
        public static string ErrorOrder {
            get {
                return ResourceManager.GetString("ErrorOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء الإتصال بمدير النظام لوجود خطأ في النظام.
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن اضافة محامي مرتين.
        /// </summary>
        public static string exist {
            get {
                return ResourceManager.GetString("exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المستخدم مدخل من قبل!.
        /// </summary>
        public static string ExistProsecuterName {
            get {
                return ResourceManager.GetString("ExistProsecuterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم أختيار هذا الشخص مع مستخدم سابق.
        /// </summary>
        public static string ExistProsecuterPerson {
            get {
                return ResourceManager.GetString("ExistProsecuterPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المستخدم موجود من قبل.
        /// </summary>
        public static string ExistUserName {
            get {
                return ResourceManager.GetString("ExistUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشخص مربوط فعلا مع مستخدم أخر.
        /// </summary>
        public static string ExistUserPerson {
            get {
                return ResourceManager.GetString("ExistUserPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى الاضافة.
        /// </summary>
        public static string FaildAdd {
            get {
                return ResourceManager.GetString("FaildAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكون ايام الدور ليست مختاره فى دور اخر.
        /// </summary>
        public static string IntersectedCycles {
            get {
                return ResourceManager.GetString("IntersectedCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يحتوى هذا الحقل على حروف عربية.
        /// </summary>
        public static string InvalidCharacterField {
            get {
                return ResourceManager.GetString("InvalidCharacterField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال تاريخ صحيح.
        /// </summary>
        public static string InValidDate {
            get {
                return ResourceManager.GetString("InValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ سابق لتاريخ اليوم.
        /// </summary>
        public static string InvalidDateLessThanToday {
            get {
                return ResourceManager.GetString("InvalidDateLessThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن تشكيل دوائر السنة القضائية الحالية و القادمة فقط.
        /// </summary>
        public static string InvalidDateMaxNextYear {
            get {
                return ResourceManager.GetString("InvalidDateMaxNextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب عدم إدخال سنة لاحقة.
        /// </summary>
        public static string InValidFutureYear {
            get {
                return ResourceManager.GetString("InValidFutureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ الحد الاقصى.
        /// </summary>
        public static string InvalidMaxDate {
            get {
                return ResourceManager.GetString("InvalidMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الحد الأقصى لأيام العطلات يومان فقط.
        /// </summary>
        public static string InValidMaxVacationNumber {
            get {
                return ResourceManager.GetString("InValidMaxVacationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يحتوى هذا الحقل على ارقام.
        /// </summary>
        public static string InvalidNumberField {
            get {
                return ResourceManager.GetString("InvalidNumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء التحقق من اسم المستخدم وكلمة المرور.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال سنة صحيحة.
        /// </summary>
        public static string InValidYearFormat {
            get {
                return ResourceManager.GetString("InValidYearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب عدم تكرار اسم القاضى.
        /// </summary>
        public static string JudgeUsedTwice {
            get {
                return ResourceManager.GetString("JudgeUsedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال تاريخ اليوم أو تاريخ لاحق.
        /// </summary>
        public static string MinDateToday {
            get {
                return ResourceManager.GetString("MinDateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أختيار جلسة.
        /// </summary>
        public static string MustSelectSession {
            get {
                return ResourceManager.GetString("MustSelectSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال اسم الاجازة.
        /// </summary>
        public static string NameFieldError {
            get {
                return ResourceManager.GetString("NameFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد شخص اخر له نفس الرقم القومى.
        /// </summary>
        public static string NatIDExist {
            get {
                return ResourceManager.GetString("NatIDExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  برجاء إدخال الرقم القومى 14 رقما فقط صحيح .
        /// </summary>
        public static string NationalIDNotValid {
            get {
                return ResourceManager.GetString("NationalIDNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إختير شخص.
        /// </summary>
        public static string NoePersonSelect {
            get {
                return ResourceManager.GetString("NoePersonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم أدخال أسم الملف!.
        /// </summary>
        public static string NoFileName {
            get {
                return ResourceManager.GetString("NoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد نتائج بحث.
        /// </summary>
        public static string NoSearchResult {
            get {
                return ResourceManager.GetString("NoSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب المستخدم غير مفعل.
        /// </summary>
        public static string NotAuthorizedAccess {
            get {
                return ResourceManager.GetString("NotAuthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرول غير مرتب.
        /// </summary>
        public static string NotOrder {
            get {
                return ResourceManager.GetString("NotOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن التعديل القضية لها رقم شامل.
        /// </summary>
        public static string NoUpdateOverAllNumberExist {
            get {
                return ResourceManager.GetString("NoUpdateOverAllNumberExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن التعديل تم تحديد جلسات للقضية.
        /// </summary>
        public static string NoUpdateThereIsASession {
            get {
                return ResourceManager.GetString("NoUpdateThereIsASession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل يقبل أرقام فقط.
        /// </summary>
        public static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنجاح.
        /// </summary>
        public static string OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تتم العملية بنجاح.
        /// </summary>
        public static string OperationNotCompleted {
            get {
                return ResourceManager.GetString("OperationNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ بيانات الخصم بنجاح.
        /// </summary>
        public static string PartyAdded {
            get {
                return ResourceManager.GetString("PartyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الشخص مسجل بالقضية كخصم.
        /// </summary>
        public static string PartyAlreadyExists {
            get {
                return ResourceManager.GetString("PartyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في الحفظ.
        /// </summary>
        public static string PartyNotAdded {
            get {
                return ResourceManager.GetString("PartyNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد رول مفتوح.
        /// </summary>
        public static string PreviousRollNotClosed {
            get {
                return ResourceManager.GetString("PreviousRollNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف وكيل النيابة لأنه مدرج فى جلسة.
        /// </summary>
        public static string ProsecutorSessionExistDelete {
            get {
                return ResourceManager.GetString("ProsecutorSessionExistDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل بيانات وكيل النيابة لأنه مدرج فى جلسة.
        /// </summary>
        public static string ProsecutorSessionExistEdite {
            get {
                return ResourceManager.GetString("ProsecutorSessionExistEdite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار المحكمة.
        /// </summary>
        public static string RequiredCourt {
            get {
                return ResourceManager.GetString("RequiredCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل اسم الدائرة.
        /// </summary>
        public static string RequiredCourtName {
            get {
                return ResourceManager.GetString("RequiredCourtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار نوع الجناية.
        /// </summary>
        public static string RequiredCrime {
            get {
                return ResourceManager.GetString("RequiredCrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الدائرة.
        /// </summary>
        public static string RequiredCycle {
            get {
                return ResourceManager.GetString("RequiredCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل القاضى الأول.
        /// </summary>
        public static string RequiredFirstJudge {
            get {
                return ResourceManager.GetString("RequiredFirstJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رقم القضية الجزئى.
        /// </summary>
        public static string RequiredFirstLevelNumber {
            get {
                return ResourceManager.GetString("RequiredFirstLevelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار النيابة الجزئية.
        /// </summary>
        public static string RequiredFirstProsecution {
            get {
                return ResourceManager.GetString("RequiredFirstProsecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل رئيس المحكمة.
        /// </summary>
        public static string RequiredHeadJudge {
            get {
                return ResourceManager.GetString("RequiredHeadJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل عدد القضاة.
        /// </summary>
        public static string RequiredJudgeCount {
            get {
                return ResourceManager.GetString("RequiredJudgeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار قسم الشرطة.
        /// </summary>
        public static string RequiredPoliceStation {
            get {
                return ResourceManager.GetString("RequiredPoliceStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار النيابة الكلية.
        /// </summary>
        public static string RequiredProsecution {
            get {
                return ResourceManager.GetString("RequiredProsecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل القاضى الثانى.
        /// </summary>
        public static string RequiredSecondJudge {
            get {
                return ResourceManager.GetString("RequiredSecondJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخل امين السر.
        /// </summary>
        public static string RequiredSecretaryHead {
            get {
                return ResourceManager.GetString("RequiredSecretaryHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن ترتيب هذا الرول.
        /// </summary>
        public static string RollNotSortable {
            get {
                return ResourceManager.GetString("RollNotSortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم فتح رول الجلسه لا يمكن حفظ الترتيب.
        /// </summary>
        public static string RollOpened {
            get {
                return ResourceManager.GetString("RollOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد جملة شهيرة بنفس العنوان .
        /// </summary>
        public static string SameName {
            get {
                return ResourceManager.GetString("SameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القضية الكلى متكرر.
        /// </summary>
        public static string SecondNumberExistBefore {
            get {
                return ResourceManager.GetString("SecondNumberExistBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب عدم تكرار امين سر.
        /// </summary>
        public static string SecretaryUsedTwice {
            get {
                return ResourceManager.GetString("SecretaryUsedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل المحضر بعد إرساله للقاضى للتصديق.
        /// </summary>
        public static string SendToJudgeMsg {
            get {
                return ResourceManager.GetString("SendToJudgeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإرسال من قبل.
        /// </summary>
        public static string SentBefore {
            get {
                return ResourceManager.GetString("SentBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تمت الموافقة على الجلسة من قبل القاضي.
        /// </summary>
        public static string SessionApprovedbyJudge {
            get {
                return ResourceManager.GetString("SessionApprovedbyJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال محضر الجلسه حتى تتمكن من إرسال المحضر.
        /// </summary>
        public static string SessionMinUnSaved {
            get {
                return ResourceManager.GetString("SessionMinUnSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجلسة غير متاحة للتعديل.
        /// </summary>
        public static string SessionNotAvilaple {
            get {
                return ResourceManager.GetString("SessionNotAvilaple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ الترتيب.
        /// </summary>
        public static string SuccessOrder {
            get {
                return ResourceManager.GetString("SuccessOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاضافة.
        /// </summary>
        public static string sucessAdd {
            get {
                return ResourceManager.GetString("sucessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnCompletedCaseAttachment {
            get {
                return ResourceManager.GetString("UnCompletedCaseAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال خصوم القضية.
        /// </summary>
        public static string UnCompletedCaseDefendent {
            get {
                return ResourceManager.GetString("UnCompletedCaseDefendent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أمر الأحالة.
        /// </summary>
        public static string UnCompletedCaseDescription {
            get {
                return ResourceManager.GetString("UnCompletedCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال مرفقات القضية من نوع ادلة ثبوت او  أمر الأحالة.
        /// </summary>
        public static string UnCompletedCaseDocument {
            get {
                return ResourceManager.GetString("UnCompletedCaseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال مرفقات القضية من نوع حرز.
        /// </summary>
        public static string UnCompletedCaseOptaimentDocument {
            get {
                return ResourceManager.GetString("UnCompletedCaseOptaimentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القضية لديها رقم شامل.
        /// </summary>
        public static string UnCompletedCaseOverAllReserved {
            get {
                return ResourceManager.GetString("UnCompletedCaseOverAllReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد أيام لم يتم تعريفها، يجب تعريفها لإتمام الحفظ.
        /// </summary>
        public static string UnFilledDays {
            get {
                return ResourceManager.GetString("UnFilledDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الدخول بهذا المستخدم من جهاز آخر.
        /// </summary>
        public static string UserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("UserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية الاجازة يجب ان يكون اكبر من تاريخ اليوم.
        /// </summary>
        public static string VacationStartDate {
            get {
                return ResourceManager.GetString("VacationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة مدخلة غير صالحة.
        /// </summary>
        public static string WrongValu {
            get {
                return ResourceManager.GetString("WrongValu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد بلغت الحد الأقصى للمحاولات و تم غلق الحساب ... لأستعادة الحساب يرجى التواصل مع مدير النظام.
        /// </summary>
        public static string YourAccountHasLooked {
            get {
                return ResourceManager.GetString("YourAccountHasLooked", resourceCulture);
            }
        }
    }
}
