//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIC.Base.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageTitles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JIC.Base.Resources.PageTitles", typeof(PageTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد دعوي جديدة.
        /// </summary>
        public static string AddCase {
            get {
                return ResourceManager.GetString("AddCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة تشكيل دائرة.
        /// </summary>
        public static string AddCircuitConfiguration {
            get {
                return ResourceManager.GetString("AddCircuitConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصديق على النقل الأدارى.
        /// </summary>
        public static string AdministrativePostApproval {
            get {
                return ResourceManager.GetString("AdministrativePostApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل ادارى.
        /// </summary>
        public static string AdministrativePostpound {
            get {
                return ResourceManager.GetString("AdministrativePostpound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات التعريفية للقضية.
        /// </summary>
        public static string CaseBasicData {
            get {
                return ResourceManager.GetString("CaseBasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القرارات و الأحكام.
        /// </summary>
        public static string CaseDecision {
            get {
                return ResourceManager.GetString("CaseDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث عن قضية.
        /// </summary>
        public static string CaseSearch {
            get {
                return ResourceManager.GetString("CaseSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصديق على محضر الجلسة.
        /// </summary>
        public static string CaseSessionApprove {
            get {
                return ResourceManager.GetString("CaseSessionApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعراض تقارير محاضر الجلسة.
        /// </summary>
        public static string CaseSessionReportsReview {
            get {
                return ResourceManager.GetString("CaseSessionReportsReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير محضر الجلسة.
        /// </summary>
        public static string CaseSessionRoll {
            get {
                return ResourceManager.GetString("CaseSessionRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد دوائر و جلسات للقضايا.
        /// </summary>
        public static string CaseSessions {
            get {
                return ResourceManager.GetString("CaseSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشكيل الدوائر وتسكين الاعضاء.
        /// </summary>
        public static string circuitconfiguration {
            get {
                return ResourceManager.GetString("circuitconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشكيل الدوائر.
        /// </summary>
        public static string Circuits {
            get {
                return ResourceManager.GetString("Circuits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين الحاليين للنظام.
        /// </summary>
        public static string CurrentUsers {
            get {
                return ResourceManager.GetString("CurrentUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد ايام الأدوار الشهرية و فواصل الأنعقاد.
        /// </summary>
        public static string Cycles {
            get {
                return ResourceManager.GetString("Cycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إثبات حضور الخصوم.
        /// </summary>
        public static string DefectsAttendance {
            get {
                return ResourceManager.GetString("DefectsAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القرارات و الأحكام.
        /// </summary>
        public static string Dicision {
            get {
                return ResourceManager.GetString("Dicision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل قضية.
        /// </summary>
        public static string EditCase {
            get {
                return ResourceManager.GetString("EditCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل البيانات التعريفية للقضية.
        /// </summary>
        public static string EditCaseBasicData {
            get {
                return ResourceManager.GetString("EditCaseBasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل تشكيل دائرة.
        /// </summary>
        public static string EditCircuitConfiguration {
            get {
                return ResourceManager.GetString("EditCircuitConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل استئناف.
        /// </summary>
        public static string EditElementaryCase {
            get {
                return ResourceManager.GetString("EditElementaryCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات شخص اعتبارى.
        /// </summary>
        public static string EditLegalPerson {
            get {
                return ResourceManager.GetString("EditLegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات شخص طبيعى.
        /// </summary>
        public static string EditNormalPerson {
            get {
                return ResourceManager.GetString("EditNormalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل معارضة.
        /// </summary>
        public static string EditObjection {
            get {
                return ResourceManager.GetString("EditObjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأستئناف.
        /// </summary>
        public static string ElementaryCase {
            get {
                return ResourceManager.GetString("ElementaryCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سداد امانة الخبير.
        /// </summary>
        public static string ExpertPayment {
            get {
                return ResourceManager.GetString("ExpertPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحكام الغيابية المجمعة.
        /// </summary>
        public static string GroupJudgment {
            get {
                return ResourceManager.GetString("GroupJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسديد الأحكام.
        /// </summary>
        public static string JudgmentOnDefendant {
            get {
                return ResourceManager.GetString("JudgmentOnDefendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة رول القاضي.
        /// </summary>
        public static string JudgRoll {
            get {
                return ResourceManager.GetString("JudgRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة المستخدمين.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وكلاء النيابة.
        /// </summary>
        public static string MangeProsecuters {
            get {
                return ResourceManager.GetString("MangeProsecuters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل قضايا لدائرة.
        /// </summary>
        public static string MoveCases {
            get {
                return ResourceManager.GetString("MoveCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعارضات.
        /// </summary>
        public static string ObjectionBasicData {
            get {
                return ResourceManager.GetString("ObjectionBasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فتح رول الجلسة.
        /// </summary>
        public static string OpenSessionRoll {
            get {
                return ResourceManager.GetString("OpenSessionRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء رقم شامل.
        /// </summary>
        public static string OverallNumber {
            get {
                return ResourceManager.GetString("OverallNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة قضية للرول.
        /// </summary>
        public static string ReJudge {
            get {
                return ResourceManager.GetString("ReJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصديق على رول الجلسة.
        /// </summary>
        public static string RollApprove {
            get {
                return ResourceManager.GetString("RollApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب رول الجلسة.
        /// </summary>
        public static string RollOrder {
            get {
                return ResourceManager.GetString("RollOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال المحضر للقاضى للتصديق.
        /// </summary>
        public static string SendToJudge {
            get {
                return ResourceManager.GetString("SendToJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محضر الجلسة.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة رول الجلسة.
        /// </summary>
        public static string SessionRoll {
            get {
                return ResourceManager.GetString("SessionRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رول الجلسة.
        /// </summary>
        public static string SessionRollReview {
            get {
                return ResourceManager.GetString("SessionRollReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث عن جلسات سابقة.
        /// </summary>
        public static string SessionSearch {
            get {
                return ResourceManager.GetString("SessionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فتح رول الجلسة.
        /// </summary>
        public static string StartingRoll {
            get {
                return ResourceManager.GetString("StartingRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمل الشهيرة.
        /// </summary>
        public static string TextPredections {
            get {
                return ResourceManager.GetString("TextPredections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعجيل من الوقف.
        /// </summary>
        public static string UrgeCaseFromSuspend {
            get {
                return ResourceManager.GetString("UrgeCaseFromSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأجازات.
        /// </summary>
        public static string Vacations {
            get {
                return ResourceManager.GetString("Vacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض بيانات قضية.
        /// </summary>
        public static string ViewCase {
            get {
                return ResourceManager.GetString("ViewCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد العطلات الأسبوعية.
        /// </summary>
        public static string WorkingDays {
            get {
                return ResourceManager.GetString("WorkingDays", resourceCulture);
            }
        }
    }
}
